### ISSUE TITLE
ModuleNotFoundError: No module named 'pyulog.libevents_parse'

### ISSUE THREAD

**Issue by Mubashir-alam** [PX4/pyulog#96]
I am trying to run `ulog_messages -h` got the follwoing error
```
Traceback (most recent call last):
  File "/home/mubashir/.local/bin/ulog_messages", line 11, in <module>
    load_entry_point('pyulog', 'console_scripts', 'ulog_messages')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mubashir/pyulog/pyulog/pyulog/messages.py", line 9, in <module>
    from .px4_events import PX4Events
  File "/home/mubashir/pyulog/pyulog/pyulog/px4_events.py", line 7, in <module>
    from .libevents_parse.parser import Parser
ModuleNotFoundError: No module named 'pyulog.libevents_parse'

```

**Comment by bkueng** [comment]
Did you initialize the submodule? `git submodule init`
